accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
 
]

blog/urls.py
from django.conf.urls import url
# -*- encoding: utf-8 -*-
from . import views

urlpatterns = [
    # /blog/ | /
    url(r'^$', 'blog.views.ArticleListView', name='blog.article_list'),
#    url(r'profiles/(?P<slug>[-\w]+)/$', 'blog.views.UserProfileDetailView', name='blog.userprofile_detail'),
	url(r'^somos/', 'blog.views.Somos', name='blog.somos'),
	url(r'^contacto/', 'blog.views.Contacto', name='blog.contacto'),
    url(r'^productos/(?P<slug>[-\w]+)/$', 'blog.views.ProductoDetailView', name='blog.producto_detail'),
    url(r'^blog/(?P<slug>[-\w]+)/$', 'blog.views.ArticuloDetailView', name='blog.articulo_detail'),
    url(r'^blog/$', views.ArticuloListView.as_view(), name='blog.articulo_list'),
    url(r'^productos/$', views.ProListView.as_view(), name='blog.pro_list'),
#    url(r'^perfil/(?P<slug>[-\w]+)/$', 'blog.views.ProfileDetailView', name='blog.profile_detail'),
    url(r'^categorias/(?P<slug>[-\w]+)/$', 'blog.views.CategoriaDetailView', name='blog.categoria_detail'),
    url(r'^fabricantes/(?P<slug>[-\w]+)/$', 'blog.views.FabricanteDetailView', name='blog.fabricante_detail'),
 #   url(r'^blog/(?P<slug>[-\w]+)/$', 'blog.views.BlogDetailView', name='blog.blog'),
#    url(r'^secciones/(?P<slug>[-\w]+)/$', 'blog.views.SectionDetailView', name='blog.section_detail'),
#    url(r'^tags/(?P<slug>[-\w]+)/$', 'blog.views.TagDetailView', name='blog.tag_detail'),
#    url(r'^trend/(?P<slug>[-\w]+)/$', 'blog.views.TrendDetailView', name='blog.trend_detail'),
#    url(r'^crear/$', views.ArticleCreateView.as_view(), name='blog.crear'),
#    url(r'^editar/(?P<slug>[-\w]+)/$', views.ArticleUpdateView.as_view(), name='blog.editar'),
#    url(r'^eliminar/(?P<slug>[-\w]+)/$', views.ArticleDeleteView.as_view(), name='blog.eliminar'),
]

qlturasur/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^$', include('blog.urls')),
    url(r'^', include('blog.urls')),
    url(r'^io/', include('accounts.urls')),
    url(r'^panel/', include(admin.site.urls)),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns.append(
        # /media/:<mixed>path/
        url(
            regex=r'^media/(?P<path>.*)$',
            view='django.views.static.serve',
            kwargs={'document_root': settings.MEDIA_ROOT}))

accounts/models.py
# -*- encoding: utf-8 -*-
import uuid
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.core.urlresolvers import reverse
from django.utils.timezone import now
from blog.models import *
import os

class UserProfile(models.Model):

    user = models.OneToOneField(settings.AUTH_USER_MODEL, null=True, blank=True)
    name = models.CharField(blank=True, max_length=200, verbose_name="Nombre")
    slogan = models.TextField(blank=True, null=True)
    body = models.TextField(blank=True, null=True)
    photo = models.ImageField(upload_to='profiles/avatar', blank=True, null=True)
    background = models.ImageField(upload_to='profiles/backgrounds', blank=True, null=True)
    create_at = models.DateTimeField(default=now, editable=False)
    update_at = models.DateTimeField(auto_now_add = False, auto_now=True, editable=False)
    slug = models.SlugField(editable=False)

    class Meta:
        verbose_name = 'Perfil de usuario'
        verbose_name_plural = 'Perfiles de usuarios'
        
    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.user.username)
        super(UserProfile, self).save(*args, **kwargs)

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import redirect
from django.core.urlresolvers import reverse
from .models import UserProfile
from blog.models import *
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password

accounts/templates/accounts/base_accounts.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-2">
            <div class="list-group">
                <a href="{% url 'accounts.editar_email' %}" class="list-group-item">Editar email</a>
                <a href="{% url 'accounts.editar_contrasena' %}" class="list-group-item">Editar contraseña</a>
                <a href="#" class="list-group-item">Editar foto</a>
            </div>
        </div>
        <div class="col-md-10">

            <section class="containerAccount">
                
            {% block accounts_content %}{% endblock accounts_content %}
            </section>



        </div>
    </div>
{% endblock content %}

accounts/templates/accounts/editar_contrasena.html
{% extends 'accounts/base_accounts.html' %}

{% block title %}Editar email{% endblock title %}

{% block accounts_content %}
    <h2 class="page-header">Editar contraseña</h2>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Actualizar contraseña</button>
        <a href="{% url 'accounts.index' %}" class="btn btn-warning" type="submit">Cancelar</a>
    </form>
{% endblock accounts_content %}

accounts/templates/accounts/editar_email.html
{% extends 'accounts/base_accounts.html' %}

{% block title %}Editar email{% endblock title %}

{% block accounts_content %}
    <h2 class="page-header">Editar Email</h2>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Actualizar Email</button>
        <a href="{% url 'accounts.index' %}" class="btn btn-warning" type="submit">Cancelar</a>
    </form>
{% endblock accounts_content %}

accounts/templates/accounts/editar_foto.html
{% extends 'accounts/base_accounts.html' %}

{% block title %}Editar foto{% endblock title %}

{% block accounts_content %}
    <h2 class="page-header">Editar Foto</h2>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Actualizar Foto</button>
        <a href="{% url 'accounts.index' %}" class="btn btn-warning" type="submit">Cancelar</a>
    </form>
{% endblock accounts_content %}

accounts/templates/accounts/gracias.html
{% extends 'base.html' %}

{% block title %}Gracias por registrarte{% endblock title %}

{% block content %}
<section class="containerAccount">
    <article class="containerForm">
        <div class="containerFormDiv">

    <h2>{{ username }} gracias por registrarte!</h2>
    <a href="{% url 'accounts.login' %}" class="btnPrincipal">INICIA SESIÓN PARA CONTINUAR</a>
{% endblock content %}

</div>
</article>
</section>   

accounts/templates/accounts/index.html
{% extends 'accounts/base_accounts.html' %}

{% block title %}Perfil de usuario{% endblock title %}

{% block accounts_content %}

<header class="containerTop">
        <div class="containerNavHeaderTop">
        </div>
        <div class="avatarPrincipal"></div>
        <h2>
            <style type="text/css">
            .avatarPrincipal{
  background: {{config.color}} url({{ MEDIA_URL }}{{ user.userprofile.photo }}) no-repeat center center!important;
background-size: 90%!important;
}
            </style>

            {{ user.username }}</h2>
        <h3></h3>
        <a href="#" class="btnPrincipal">ÚNETE</a>

        <div class="containerNavHeader">


        <li class="navPrincipalLeftLi"><a href=""><span class="navPrincipalLogo" id="navPrincipalLogoS" ></span></a></li>
       
        </div>

</header>

<section class="containerMiddle">

    <h5 class="titles01">
        Explora Experiencias
        <a href="#">Más Experiencias</a>
    </h5>

    {% for article in article %}

    <article class="articleContainer">
        <div class="articleTop">
            <p>El {{ article.create_at|date:'d F Y' }}<span>Hace {{ article.create_at|timesince }}</span></p>
        </div>
        <a href="{% url 'blog.article_detail' article.slug %}"><div class="articleImg" id="articleImg{{article.id}}"></div></a>
        <h4 class="articleTitle"><a href="{% url 'blog.article_detail' article.slug %}">{{ article.title }}</a></h4>

        <div class="articleBody">
            <p>{{ article.body|safe }}</p>
        </div>

        <div class="articleBottom">
            <a href="#" class="articleOwner">Por: {{ article.owner.username }}</a>
        </div>
    </article>
    {% endfor %}

</section>  
{% endblock accounts_content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock title %}

{% block content %}

<section class="forma">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="page-header"><h2>IO</h2></div>
            {% if mensaje %}
                <div class="alert alert-danger">
                    {{ mensaje }}
                </div>
            {% endif %}

            <form method="post" action="">
                {% csrf_token %}
                <div class="form-group">
             <!--       <label class="control-label" for="username">Nombre de usuario</label> -->
                    <input placeholder="Username" type="text" id="username" name="username" class="form-control" value="{{ username }}">
                </div>
                <div class="form-group">
                <!--    <label for="password">Contraseña</label> -->
                    <input placeholder="Key"  type="password" name="password" id="password" class="form-control">
                </div>
                <button type="submit" class="look">Continue IO</button>
            </form>
        </div>
    </div>

    <p class="loginBottom">¿Dont playing yet? <a href="{% url 'accounts.registro'%}">+ New IO</a></br> <p class="loginBottom"><a href="{% url 'accounts.registro'%}">¿Lost key?</a></br><a href="/">Back</a></p>

</section>

        <!--MENU BOTTOM -->
        <a href="/"><section class="formBack"></section></a>

{% endblock content %}

accounts/templates/accounts/registro.html
{% extends 'base.html' %}

{% block title %}Login{% endblock title %}

{% block content %}
{% for config in config %}
<style type="text/css">
.page-header{
    background: {{config.color01}}!important;
}
.formBack{
    background: {{config.color}} url(/media/{{config.logo}}) no-repeat center center!important;
    background-size: auto 80%!important;
}
.look{
    background: url(/static/img/icons/6.png) {{config.color02}} no-repeat 10px center!important;
    background-size: 30px!important;
}
#id_body{
    border: 3px solid {{config.color02}};
}
#id_section{
    border: 3px solid {{config.color02}};
}
#id_title{
    border: 3px solid {{config.color02}};
}
</style>
{%endfor%}

<section class="forma">
    <article class="containerForm">
        <div class="containerFormDiv">

    <div class="row">
        <div class="col-md-6 col-sm-offset-3">
            <div class="page-header">
                <h2>+IO</h2>
            </div>

            <form method="post" action="" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="look">NEW IO</button>
            </form>
        </div>
    </div>

     <p class="loginBottom">¿Already IO? <a href="{% url 'accounts.login'%}">Continue IO</a></br><a href="/">Back</a></p>

      <!--MENU BOTTOM -->
        <a href="/"><section class="formBack"></section></a>

</div>
</article>
</section>   


{% endblock content %}